spring:
 #resources:
  #static-locations: file:///C:/Users/ybhargava/SpringCloud/UIXmlValidator/src/main/resources/static
  #cache:
   #period: 0
 mvc:
  view:
   suffix: .html
logging:
 level:
  org:
   springframework:
    web: INFO
 file: xmlvalidator.log
